name: HqngOrder
version: '${version}-${gitCommit}'
main: tech.qhuyy.hqngOrder.HqngOrder
api-version: '1.21.8'
load: STARTUP
folia-supported: true
authors: [ hqng05 ]
website: https://qhuyy.tech

libraries:
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0
  - com.zaxxer:HikariCP:5.1.0

commands:
  orders:
    description: Main command for HqngOrder - opens the market GUI
    usage: /<command> [admin|reload]
    aliases: [ order, hqngo, horder ]

permissions:
  hqngorder.use:
    description: Allows the player to use the /orders command and access the market
    default: true
  hqngorder.admin:
    description: Grants access to admin commands (/orders admin, /orders reload) and the admin panel
    default: op
